# Metadatos del Proyecto
sonar.organization=tonyua2023
sonar.projectKey=tonyua2023_planner-uc
sonar.projectName=Planner-UC
sonar.projectVersion=3.0.0

# Rutas del Código Fuente y Pruebas
sonar.sources=backend, frontend/src
sonar.tests=backend/tests, frontend/tests

# Exclusiones de Análisis
sonar.exclusions=**/node_modules/**, **/dist/**, **/cypress/**, **/playwright-report/**, **/test-results/**, backend/backend-integration-report.json, backend/tests/**

# Codificación de Archivos
sonar.sourceEncoding=UTF-8

# Reportes de Cobertura de Pruebas
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info, frontend/coverage/lcov.info
